### ISSUE TITLE
ST4 CTRL+ALT+J not working

### ISSUE THREAD

**Issue by DavidLanz** [dzhibas/SublimePrettyJson#139]
Fresh install Pretty JSON through Package Install on ST4
And try CTRL+ALT+J not working

but it was fine on ST3

**Comment by Chanpreet08** [comment]
+1

**Comment by saurabh-cimpress** [comment]
+1 On Mac

**Comment by TheSecEng** [comment]
I will update the read me, but we removed the key bindings and it is now the end users job to create them. This is due to the fact that they were conflicting with many other keybindings present in ST and we want to minimize the conflicting keybindings.

**Comment by webern** [comment]
+1

I am reading the Sublime Text documentation but I can't find an example of how to create a key binding to a command that is otherwise accessed in the command palette. Here's what I have tried, but it's just a guess (and it doesn't work). I think putting the example of exactly how to do this would be a great service to users who are sad that command-shift-j is gone.

```json
    {
        "keys":
        [
            "super+shift+j"
        ],
        "command": "command_palette",
        "args":
        {
            "Pretty JSON": "Format JSON"
        }
    }
```

**Comment by webern** [comment]
OK, I followed the instructions here: https://stackoverflow.com/questions/11834652/bind-shortcut-to-command-palette-command and found that the command name is `pretty_json`, and this works:

```json
{ "keys": ["super+shift+j"], "command": "pretty_json" }
```

**Comment by nikoudel** [comment]
For windows:
```json
{ "keys": ["ctrl+alt+j"], "command": "pretty_json" }
```
