### ISSUE TITLE
validate_on_save not work

### ISSUE THREAD

**Issue by mercurykd** [dzhibas/SublimePrettyJson#168]
"pretty_on_save": true,
"validate_on_save": true,

not work

windows 11, ST4 4126

**Comment by mercurykd** [comment]
if you install the extension manually via git, and manually reload the Pretty JSON.PrettyJsonListeners module in the console after the start, then it will work

**Comment by jbartolozzi** [comment]
having the same issue

**Comment by User-3090** [comment]
how does this fix the issue? why is closed? can't the package be fixed on package control? If a package offers settings, they should work.

**Comment by FichteFoll** [comment]
This package uses `sublime.load_settings` at module import time, which ST3 and 4 generally did not guarantee to work. Only since build 4180 this is reliable because the API will always be ready when Python plugins are imported.

Everyone affected by this issue should update to build 4180 or later (or the code needs to be fixed to load the settings during `plugin_loaded`).
