### ISSUE TITLE
Cannot save preferences anymore after update to build 4180

### ISSUE THREAD

**Issue by WoodrowShigeru** [dzhibas/SublimePrettyJson#185]
I could determine in safe mode that it's a Pretty JSON error.

Regression: sublime used to internally preconvert / parse / (don't know the right term) the user preferences from a "lax" JSON to a strict JSON. For user convenience like comments.

It doesn't do that anymore. The syntax highlighting now also says straight up "json". IIRC, it used to say something with "sublime" in it too … "sublime settings file" or something. That entry is missing in the syntax highlighting list.

Because of that, the app now complains about trailing commas on the last item, and comments when I try to save the settings.

Same for keymaps / key bindings and color schemes, of course.

As a workaround, (I am manually removing all trailing commas and) I rewrite comments for now as such: `"comment1": "// Package: Markdown Editing.",`

---

**Sublime:** 4180
**OS:** Ubuntu 22.04.4 LTS
**Desktop environment:** GNOME 42.9

**Comment by deathaxe** [comment]
This is caused by Pretty JSON now correctly handling `on_post_save` events due to a fixed event listener (see #184) to fix issue #172, #180.

You probably want to...

1. disable "pretty_on_save"` setting
2. or remove ST related JSONC files from `"as_json"` as this plugin can't correctly handle them.

   see: https://github.com/dzhibas/SublimePrettyJson/blob/382534afc7c708c4e64ddd7225728fc1748a6348/Pretty%20JSON.sublime-settings#L25-L27

**Comment by deathaxe** [comment]
As a side note: This issue is not related with any ST build. It's not 4180 to blame.

**Comment by WoodrowShigeru** [comment]
Thanks for the clarification, and quick fix. The issue only popped up for me right after updating Sublime to 4180, hence my assumption.

**Comment by muya** [comment]
Another side effect of this: 

> If `ensure_newline_at_eof_on_save` is enabled in Sublime Text settings, saving a JSON file results in removal of the newline on save.

Disabling `on_post_save` in PrettyJSON settings resolves this issue as well.
