### ISSUE TITLE
./jq under osx does not work

### ISSUE THREAD

**Issue by dzhibas** [dzhibas/SublimePrettyJson#37]
some kind of bug, that subprocess.Popen cannot find jq installed through brewer. maybe  problems with path

**Comment by chrispauley** [comment]
Not working for osx, st3
Tried installing through package control, then through git clone. Both receive the same error.

The feature shows up in Tools-->Command Pallete-->Pretty JSON: JSON query with ./js
Message from st3 indicates
./js tool is not available on your system http://stedolan.github.io/jq

**Comment by jonnolen** [comment]
I was also running into this issue, in my case the path solution of manually adding /usr/local/bin wasn't sufficient because we use boxen and it changes the homebrew install paths.

I was able to fix it by adding the "Fix Mac Path" (https://github.com/int3h/SublimeFixMacPath) package, and then making the changes in #61, to defer the jq existence check until the user requests ./jq the first time.

**Comment by dzhibas** [comment]
PR #61 merged in and also made some win32 platform fixes, hopefully that fixes all issues mentioned in this issue thread
